export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';